### ISSUE TITLE
Poor UX; overly complicated

### ISSUE THREAD

**Issue by pcj** [puppeteer/pptr.dev#15]
The "Loading first time" takes forever and does not finish for me.

Please just revert the API documentation website to simple static HTML and an opt-in for the fancier website (that I cannot visit).

**Comment by theDavidBarton** [comment]
About the loading is not finished: there are known site errors with Firefox (incognito mode or strict privacy settings in normal mode), most probably related to IndexedDB https://github.com/puppeteer/pptr.dev/issues/3 https://github.com/puppeteer/pptr.dev/issues/13 https://github.com/puppeteer/pptr.dev/issues/12.

For a functional site a Chromium based browser or normal mode in Firefox will take it until the above listed issues are not fixed for good.

As a workaround all the official docs are also available on GitHub: [docs/api.md](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md)
