### ISSUE TITLE
Website (https://pptr.dev/) is not loading

### ISSUE THREAD

**Issue by akshaykhale1992** [puppeteer/pptr.dev#28]
pptr.dev is not loading, it's simply showing the Default Loading Page.

When I checked the browser console, I found these 2 errors:
- Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations.
- Uncaught (in promise) DOMException: The quota has been exceeded.

**Comment by theDavidBarton** [comment]
About the loading is not finished: there are known site errors with **Firefox browser** (incognito mode or strict privacy settings in normal mode), most probably **related to IndexedDB** https://github.com/puppeteer/pptr.dev/issues/3 https://github.com/puppeteer/pptr.dev/issues/13 https://github.com/puppeteer/pptr.dev/issues/12.

For a functional site, a Chromium-based browser or normal mode in Firefox will take it until the above-listed issues are not fixed for good.

As a workaround, all the official docs are also available on GitHub: [docs/api.md](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md)

**Comment by OrKoN** [comment]
Does it still happen? we have released a new website since then.
