### ISSUE TITLE
pptr.dev search the docs is not working

### ISSUE THREAD

**Issue by original-taste** [puppeteer/pptr.dev#32]
![image](https://user-images.githubusercontent.com/54194460/200004271-f1acebe3-0f3f-4f75-b5f1-aa8971d11bc9.png)
![image](https://user-images.githubusercontent.com/54194460/200004579-07e40829-a7a4-4d28-9f51-11ae40fb180a.png)

The inbuild search system in pptr.dev webpage is showing "No results" for everything.

**Comment by OrKoN** [comment]
@original-taste can you retry? I believe 3 days ago it was when Algolia was deployed so the index was being created at the time.
